# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#


# TODO: This is a placeholder, probably broken and needs to be tested out.
platform :ios do
  desc "Build the project"
  lane :build do
    gym()
  end

  desc "Run unit tests"
  lane :tests do
    scan()
  end
end
