# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

SIGNING_TYPES = ["adhoc", "appstore", "development"]


platform :ios do
  desc "Syncs the signing certificates and provisioning profiles"
  lane :signing_get do
    SIGNING_TYPES.each {
      match(
        readonly: true,
        type: _1
      )
    }
  end

  desc "Sets the signing certificates and provisioning profiles"
  lane :signing_update do
    SIGNING_TYPES.each {
      match(
        force_for_new_devices: true,
        include_mac_in_profiles: true,
        type: _1
      )
    }
  end
end
